#!/usr/bin/env node
/**
 * Bundle the club ratings into App B at build time.
 *
 * App B is a single self-contained HTML file that must open on a phone with no
 * dev server and no network. So the ratings it needs travel with it, taken from
 * the newest committed outlook artefact — the same artefact App A reads, so the
 * two cannot disagree about a club's strength.
 *
 * The season is discovered, never hardcoded (§5.5).
 */
import fs from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../../..");
const SEASONS = path.join(ROOT, "data", "seasons");
const OUT = path.resolve(import.meta.dirname, "../src/generated");

const exists = async (p) => { try { await fs.access(p); return true; } catch { return false; } };

const clubs = new Map();
let newest = null;
let params = null;

try {
  params = JSON.parse(await fs.readFile(path.join(ROOT, "data", "season-params.json"), "utf8"));
} catch {
  params = null;
}

if (await exists(SEASONS)) {
  const dirs = (await fs.readdir(SEASONS, { withFileTypes: true }))
    .filter((d) => d.isDirectory()).map((d) => d.name).sort();
  for (const season of dirs) {
    for (const league of ["bl1", "bl2"]) {
      const outlookPath = path.join(SEASONS, season, league, "outlook.json");
      const seasonPath = path.join(SEASONS, season, league, "season.json");
      if (!(await exists(outlookPath)) || !(await exists(seasonPath))) continue;
      const outlook = JSON.parse(await fs.readFile(outlookPath, "utf8"));
      const seasonData = JSON.parse(await fs.readFile(seasonPath, "utf8"));
      newest = Number(season);
      for (const club of seasonData.clubs) {
        const rating = outlook.ratings?.[club.clubId];
        if (Number.isFinite(rating)) {
          clubs.set(club.clubId, { clubId: club.clubId, name: club.name, league, rating });
        }
      }
    }
  }
}

await fs.mkdir(OUT, { recursive: true });
await fs.writeFile(
  path.join(OUT, "clubs.json"),
  `${JSON.stringify({
    _comment: "Generated by scripts/generate-clubs.mjs — do not edit. Ratings come from the "
      + "committed outlook artefact, so App A and App B cannot disagree about a club's strength.",
    season: newest,
    generatedAt: new Date().toISOString().slice(0, 10),
    params: params?.params ?? null,
    procedureVersion: params?.procedureVersion ?? null,
    clubs: [...clubs.values()].sort((a, b) => a.name.localeCompare(b.name, "de")),
  }, null, 2)}\n`,
);

process.stderr.write(
  clubs.size
    ? `bundled ${clubs.size} clubs from season ${newest}\n`
    : "no committed ratings found — App B will require manual rating entry\n",
);
